# implement sanity checks before configuration
# examples
# - Is it a supported OS
# - do you really want to run a t2-micro?
# - does the machine have the necessary provisioning tags? 
- name: "Capture pre-config state"
  become: yes
  shell: |
    #!bin/bash 
    SNAP_DIR=/var/log/yum-snapshots 
    SNAP_PRE_DATE=$(date +"%Y-%m-%d-%H-%M")
    SNAP_PRE_FILE=$SNAP_DIR/$SNAP_PRE_DATE-pre.txt
    mkdir -p $SNAP_DIR 
    yum list installed > $SNAP_PRE_FILE

